const constants = {
  PROGRESS: "PROGRESS",
  SIGNIN: "SIGNIN",
  SIGNUP: "SIGNUP",
  SIGNIN_SUCESS: "SIGNIN_SUCESS",
  SIGNIN_FAILED: "SIGNIN_FAILED",
  SIGNUP_PROGRESS: "SIGNUP_PROGRESS",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILED: "SIGNUP_FAILED",
};

export default constants;
